# Unique name for this workflow
name: Gen2 Package on Release
on:
  release:
    types: [published, created, edited]
  workflow_dispatch:
# Jobs to be executed
jobs:
  parse-config:
    runs-on: ubuntu-latest
    outputs:
      sfdxpackage: ${{ steps.parse-package.outputs.packageJson }}
    steps:
      - name: 'Parse sfdx-package.json'
        id: parse-package
        run: |
          content="cat sfdx-project.json"
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"
          echo "packageJson=$content" >> $GITHUB_OUTPUT

  salesforce-authentication:
    runs-on: ubuntu-latest
    needs: parse-config
    steps:
      # Checkout the code in the pull request
      - name: 'Checkout source code'
        uses: actions/checkout@v4
        with:
          ref: 'main'
        run: |
          echo "${{ steps.parse-package.outputs.content}}"
          env_data=${{ fromJson(steps.package.outputs.content) }}
          echo "env_data=$env_data"
          echo $env_data.namespace
