# Unique name for this workflow
name: Gen2 Packaging
on:
  release:
    types: [published, created, edited]
  workflow_dispatch:
  push:
# Jobs to be executed
jobs:
  parse-config:
    runs-on: ubuntu-latest
    outputs:
      sfdxpackage: ${{ steps.parse-package.outputs.packageJson }}
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: 'Parse sfdx-package.json'
        id: parse-package
        run: |
          content="cat sfdx-project.json"
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          #echo "::set-output name=packageJson::$content"
          #echo "packageJson=$content" >> $GITHUB_OUTPUT
          namespace=$($content | jq '.namespace')
          echo "namespace=$namespace" >> $GITHUB_OUTPUT
          echo "$namespace"
      - name: 'Verify output'
        id: verify-output
        run: |
          echo ${{steps.parse-package.outputs.namespace}}
          #echo "${{ steps.parse-package.outputs.namespace}}"
