name: release-please
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
  actions: 'write'
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: 'Release Please Action'
        id: release-please
        uses: google-github-actions/release-please-action@a6d1fd9854c8c40688a72f7e4b072a1e965860a0 # v4
        with:
          command: manifest
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: sfdx
      - name: 'Checkout source code'
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          ref: 'main'
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci
      - name: 'Check if release created'
        id: release-check
        if: ${{ ! steps.release-please.outputs.releases_created }}
        run: |
          echo "No release created."
          #gh run cancel ${{ github.run_id }}
          #gh run watch ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Run on release creation'
        if: ${{ steps.release-please.outputs.releases_created }}
        run: echo "Release created"
      - name: 'Update ApexDox'
        id: update-apex-dox
        if: ${{ steps.release-please.outputs.releases_created }}
        run: |
          git config user.email "${{ github.repository_owner }}@users.noreply.github.com"
          git config user.name "${{ github.repository_owner }}"
          . doc-assets/updateChangelog.sh
      - name: 'Commit changes'
        id: auto-commit-action
        if: ${{ steps.release-please.outputs.releases_created }}
        uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d # v5
        with:
          commit_message: 'docs: update ApexDox for release ${{ steps.release-please.outputs.major }}.${{ steps.release-please.outputs.minor }}.${{ steps.release-please.outputs.patch }}'
