name: release-please
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: 'Release Please Action'
        id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          release-type: sfdx
      - name: 'Display release-please outputs'
        run: echo "${{join(steps.release-please.outputs.*, '\n')}}""
      - name: 'Check if package created'
        id: package-check
        if: steps.release-please.outputs.releases_created != true
        run: |
          echo "No package created. Exiting."
          exit 0
      - name: 'Run on package creation'
        if: steps.release-please.outputs.releases_created == true
        run: |
          . doc-assets/updateChangelog.sh
