name: release-please
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
  actions: 'write'
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: 'Release Please Action'
        id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: sfdx
      - name: 'Checkout source code'
        uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: 'Check if release created'
        id: release-check
        if: ${{ ! steps.release-please.outputs.releases_created }}
        run: |
          echo "No release created."
          #gh run cancel ${{ github.run_id }}
          #gh run watch ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Run on release creation'
        if: ${{ steps.release-please.outputs.releases_created }}
        run: echo "Release created"
      - name: 'Checkout source code'
        uses: actions/checkout@v4
        if: ${{ steps.release-please.outputs.releases_created }}
      - name: 'Update ApexDox'
        id: update-apex-dox
        #if: ${{ steps.release-please.outputs.releases_created }}
        run: |
          git config user.email "${{ github.repository_owner }}@users.noreply.github.com"
          git config user.name "${{ github.repository_owner }}"
          npm install --save-dev prettier
          . doc-assets/updateChangelog.sh
          rm docs/changelog.html
      - name: 'Commit changes'
        #if: ${{ steps.release-please.outputs.releases_created }}
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: update changelog on release ${{ github.run_id }}-${{ github.run_attempt }}'
