name: release-please
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: 'Release Please Action'
        id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: sfdx
      - name: 'Check if release created'
        id: release-check
        if: steps.release-please.outputs.releases_created == false
        run: |
          echo "No release created."
      - name: 'Run on release creation'
        if: steps.release-please.outputs.releases_created == true
        run: echo "Release created"
      - name: 'Checkout source code'
        uses: actions/checkout@v4
      - name: 'Update ApexDox'
        id: update-apex-dox
        #if: steps.release-please.outputs.releases_created == true
        run: |
          git config user.email "${{ github.repository_owner }}@users.noreply.github.com"
          git config user.name "${{ github.repository_owner }}"
          . doc-assets/updateChangelog.sh
      - name: 'Commit changes'
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: update changelog on release'
